services:
  api:
    env_file:
      - .env.prod
    build:
      target: prod
  
  worker:
    env_file:
      - .env.prod
  
  beat:
    env_file:
      - .env.prod
  
  frontend:
    env_file:
      - .env.prod
    build:
      target: prod
  
  nginx:
    ports:
      - "${NGINX_PORT}:80"